export const SET_USER_DATA = 'auth/SET_USER_DATA'
export const SET_REG_DATA = 'auth/REG_USER_DATA'

export const SEARCH_MODE = 'SEARCH/SEARCH_MODE'
export const SET_USERS = 'SEARCH/SET_USERS'


export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const REQUEST_MESSAGES = 'REQUEST_MESSAGE'